#+OPTIONS: ^:nil
#+BEGIN_EXPORT html
---
layout: default
title: 创客利器之ESP32（一）
tags: [esp32, MCU]
nav_order: {{ page.date }}
---
#+END_EXPORT

* 什么是ESP32？
ESP32狭义上指的是乐鑫信息科技推出的一类面向物联网应用的嵌入式SoC(System
on Chip)芯片，广义上还可以指基于ESP32的软硬件产品。ESP32芯片基于Xtensa LX6
32-bit处理核心研发，并增加Wifi等无线通讯功能，具有单核和双核等不同版本。芯片本身就支持Wifi、蓝牙、
USB、GPIO等多种无线和有线接口，不需要再增加接口芯片。可以方便地应用于
智慧农业、工业检测、智能家居等
IoT场景。这种身材灵巧并且功能强大的芯片很受创客社区的欢迎。在Arduino、CircuitPython等开发平台中
都增加了对ESP32的支持。乐鑫和创客社区推出了很多具有USB接口的开发板，
插入电脑即可编程，非常方便。有Arduino和Python编程经验的人，可以很快掌握如何在
项目中使用ESP32模块。ESP32是一款容易上手且功能强大的物联网芯片，既适合
电子爱好者也适合专业人士，有广阔的应用前景。

* ESP32可以用来做什么？
因为ESP32支持丰富接口协议，和丰富的应用程序库esp-idf，开发者可以很快地
开发出应用程序，不需要详细了解底层硬件协议。ESP32可以用来控制智能小车、
智能电路、智能手表等，用户可以根据自己的创意开发新的使用场景。国内外的创
客基于ESP32开发了很多个创意项目，下面列出一些基于ESP32制作的有趣项目。
1. ESP32小车
2. ESP32手表
3. ... /hackday.io ESP32/
我们可以利用ESP32帮助我们控制家里的电器、自动投喂宠物等等功能，具体能做什
么取决于使用者的想象力。

* 快速玩转ESP32
乐鑫提供了esp-idf环境和ESP32应用程序库，提供给开发者使用，不过需要使用
者有一定的编程经验。最近由于arduino-esp32开源社区的努力，我们现在可以使用Arduino软件来编写
ESP32程序，将ESP32的使用门槛降低了不
少。下面我们通过一个例子介绍使用Arduino来开发ESP32程序。我们的任务是用ESP32演奏一段“欢乐颂”。首先我们需要先准备下列硬件：
1. ESP32开发版（type-c和mini-usb接口的都可以）
2. 蜂鸣器
3. 导线若干
4. USB-A转换线（根据开发板的接口类型选择）
市面上有很多ESP32开发板。乐鑫科技自己也有ESP32开发板，还有很多小公司和
个人推出的克隆板。淘宝上面很多，大约二十元到五十元不等，都可以使用。
准备好硬件后，我们可以开始准备开发程序了。这里使用Mac上的Arduino软件作为示例，PC上的操作步骤应该也类似。Arduino软件默认
只支持Arduino系列开发版，我们还需要做一些配置使得Arduino支持ESP32。不
过不用担心，步骤比较简单。
/描述如何配置Arduino，支持ESP32开发板/



* 总结
这是ESP32系列的第一篇，介绍了什么是ESP32以及如何使用Arduino环境
对ESP32进行编程。后面我们还会继续这个主题，尝试一些其他实验，比如在ESP32上运行Python，
使用ESP32模拟一个键盘等。


- 什么是ESP32？
